### ISSUE TITLE
examplar dataset 

### ISSUE THREAD

**Issue by zhongyuan1995** [AmigoCap/ReViVD#35]
Hi, awesome work! May I get some examplar datasets from you? Thanks!

**Comment by yohhaan** [comment]
Hi,

Thanks for your interest in ReViVD!

We are not able to publicly share the datasets we used for our visualizations for access restrictions reasons.
However, following our online documentation you will be able to quite easily import any dataset of trajectories into ReViVD. You need to create a binary file with the data and a json file describing the dataset. You will find an example and explanations here: https://amigocap.github.io/ReViVD/documentation/

Best,

Yohan
